# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GodotBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Make export templates directory
        run: mkdir -p "/home/runner/.local/share/godot/export_templates"
      - name: Download Godot
        run: wget "https://github.com/MarkusSecundus/Gamestudies-Experiment/releases/download/godot-binary/godot"  ; chmod 777 ./godot
      - name: Download export templates
        run:  wget "https://downloads.godotengine.org/?version=4.5.1&flavor=stable&slug=export_templates.tpz&platform=templates"
      - name: Extract export templates
        run: ls -l ; unzip 'index.html?version=4.5.1&flavor=stable&slug=export_templates.tpz&platform=templates' -d "/home/runner/.local/share/godot/export_templates"
      - name: Build
        run: ./godot --headless --verbose --export-release "win64" ./win64.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - win64.exe
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
